// <auto-generated />
namespace ToeicAspMVC.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class newa : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(newa));
        
        string IMigrationMetadata.Id
        {
            get { return "202210271605251_new-a"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
